### ISSUE TITLE
你好，我按照你的代码使用多语言，但是切换语言的时候，只切换了屏幕上的语言翻译，请问是怎么回事呢？

### ISSUE THREAD

**Issue by Clearlee** [aijason/RN_WanAndroid#2]
比如我从中文切换到英语，只切换成功了屏幕上的内容，当我切换底部tab到其他页面，其他页面的内容并没有翻译，请问是怎么回事呢？语言都配置好了的。

**Comment by aijason** [comment]
这个问题有遇到，我是在其他页面上，引入了语言切换时store里的language字段解决的。相当于切换语言时，各个页面做了刷新。应该有更好的处理方式，期待你的方法。
